services:
  postgres:
    image: postgres:17
    container_name: zarrine-postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mahditd0010td00010
      POSTGRES_DB: zarrine_baft

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: